//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("fcopy ver:1.4.21127.2")]
[assembly: AssemblyDescription("copies files based onspecified conditions.")]
[assembly: AssemblyCompany("Bricksoft.com")]
[assembly: AssemblyProduct("fcopy")]
[assembly: AssemblyCopyright("Copyright (C) 2006-2012 Kody Brown.")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("97975137-DA08-4EA3-8F80-B85E1438CCF7")]
[assembly: AssemblyVersion("1.4.21127.2")]
[assembly: AssemblyFileVersion("1.4.21127.2")]


